version: 2.1

orbs:
  python: circleci/python@1.3.0

jobs:
  build-and-test:
    executor:
      name: python/default

    steps:
        - checkout
        - run:
            command: pip install --user JEGmail
            name: pip JEGmail
        - run:
            command: pip install --user google-api-python-client
            name: pip google-api-python-client
        - run:
            command: pip install --user google-auth-httplib2
            name: pip google-auth-httplib2
        - run:
            command: pip install --user google-auth-oauthlib
            name: pip google-auth-oauthlib
        - run:
            command: python Test/Gmail_Test.py
            name: Test
        - run:
            command: python Test/UnitTest.py
            name: UnitTest

workflows:
  main:
    jobs:
      - build-and-test